name: Deployment script
run-name: Deployment Runner 
on: [push, workflow_dispatch]

env:
  IMAGE_NAME: ${{secrets.REGION_ID}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/appengine1-repository/cicdtest
  VPC_CONNECTOR: eva-modeller
  REGION_ID: europe-west1

jobs:
  deployment:
    if: contains( 'refs/heads/development', github.ref)
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
    - name: Setting up environment for build...
      run: |
        apk add --no-cache git maven bash curl wget
        apk --no-cache add openjdk17-jdk
        apk add --no-cache python3 py3-pip
    
    - name: Checking out the code...
      uses: actions/checkout@v3
    
    - name: Github authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{secrets.SERVICE_ACCOUNT_KEYFILE_JSON}}
      
    - name: Building project...
      run: |
        cp .m2/settings.xml .m2/settings.xml.tmp
        sed -i 's/${ARTIFACTORY_USER}/${{secrets.ARTIFACTORY_USER}}/' .m2/settings.xml.tmp
        sed -i 's/${ARTIFACTORY_PASS}/${{secrets.ARTFICATORY_PASS}}/' .m2/settings.xml.tmp
        more .m2/settings.xml
        more .m2/settings.xml.tmp
